<?php

namespace Database\Seeders;

use Framework\Seeder;
use App\Models\Product;
use App\Models\Category;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $this->clearTable('products');

        $products = [
            // Electronics
            [
                'name' => 'Premium Wireless Headphones',
                'slug' => 'premium-wireless-headphones',
                'description' => 'High-quality wireless headphones with noise cancellation and premium sound quality.',
                'price' => 299.99,
                'sale_price' => 249.99,
                'category_id' => $this->getCategoryId('electronics'),
                'images' => [
                    '/public/images/products/premium-wireless-headphones-1.jpg',
                    '/public/images/products/premium-wireless-headphones-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 50,
                'sku' => 'PWH-001',
                'weight' => 0.3,
                'length' => 20.0,
                'width' => 15.0,
                'height' => 8.0,
                'attributes' => json_encode([
                    'driver_size' => '40mm',
                    'frequency_response' => '20Hz - 20kHz',
                    'impedance' => '32 ohms',
                    'battery_life' => '30 hours',
                    'connectivity' => 'Bluetooth 5.0',
                    'noise_cancellation' => 'Active'
                ]),
                'meta_title' => 'Premium Wireless Headphones - Noise Cancelling',
                'meta_description' => 'Experience premium sound with our wireless headphones featuring active noise cancellation.',
                'meta_keywords' => 'headphones, wireless, noise cancellation, premium audio',
            ],
            [
                'name' => 'Smart Bluetooth Speaker',
                'slug' => 'smart-bluetooth-speaker',
                'description' => 'Portable smart speaker with voice assistant integration and 360-degree sound.',
                'price' => 199.99,
                'sale_price' => null,
                'category_id' => $this->getCategoryId('electronics'),
                'images' => [
                    '/public/images/products/bluetooth-speaker-pro-1.jpg',
                    '/public/images/products/bluetooth-speaker-pro-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 75,
                'sku' => 'SBS-002',
                'weight' => 0.8,
                'dimensions' => '15x15x15 cm',
                'meta_title' => 'Smart Bluetooth Speaker - Voice Assistant',
                'meta_description' => 'Portable smart speaker with voice assistant and 360-degree sound.',
                'meta_keywords' => 'speaker, bluetooth, smart, voice assistant',
            ],
            [
                'name' => 'Wireless Charging Pad',
                'slug' => 'wireless-charging-pad',
                'description' => 'Fast wireless charging pad compatible with all Qi-enabled devices.',
                'price' => 79.99,
                'sale_price' => 59.99,
                'category_id' => $this->getCategoryId('electronics'),
                'images' => [
                    '/public/images/products/wireless-charger-pad-1.jpg',
                    '/public/images/products/wireless-charger-pad-2.jpg'
                ],
                'featured' => false,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 100,
                'sku' => 'WCP-003',
                'weight' => 0.2,
                'dimensions' => '10x10x1 cm',
                'meta_title' => 'Wireless Charging Pad - Qi Compatible',
                'meta_description' => 'Fast wireless charging pad for all Qi-enabled smartphones and devices.',
                'meta_keywords' => 'wireless charging, qi, charging pad, fast charge',
            ],
            [
                'name' => 'USB-C Multi-Port Hub',
                'slug' => 'usb-c-multi-port-hub',
                'description' => 'Compact USB-C hub with multiple ports for laptops and tablets.',
                'price' => 89.99,
                'sale_price' => null,
                'category_id' => $this->getCategoryId('electronics'),
                'images' => [
                    '/public/images/products/usb-c-multi-port-hub-1.jpg',
                    '/public/images/products/usb-c-multi-port-hub-2.jpg'
                ],
                'featured' => false,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 60,
                'sku' => 'UCM-004',
                'weight' => 0.15,
                'dimensions' => '8x3x1 cm',
                'meta_title' => 'USB-C Multi-Port Hub - Compact Design',
                'meta_description' => 'Expand your laptop connectivity with this compact USB-C multi-port hub.',
                'meta_keywords' => 'usb-c, hub, multi-port, laptop, connectivity',
            ],
            [
                'name' => 'Bluetooth Adapter USB',
                'slug' => 'bluetooth-adapter-usb',
                'description' => 'Plug-and-play Bluetooth adapter for computers and laptops.',
                'price' => 29.99,
                'sale_price' => 19.99,
                'category_id' => $this->getCategoryId('electronics'),
                'images' => [
                    '/public/images/products/bluetooth-adapter-usb-1.jpg',
                    '/public/images/products/bluetooth-adapter-usb-2.jpg'
                ],
                'featured' => false,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 120,
                'sku' => 'BAU-005',
                'weight' => 0.05,
                'dimensions' => '3x1x0.5 cm',
                'meta_title' => 'Bluetooth Adapter USB - Plug and Play',
                'meta_description' => 'Add Bluetooth connectivity to any computer with this USB adapter.',
                'meta_keywords' => 'bluetooth, adapter, usb, computer, connectivity',
            ],
            [
                'name' => 'Monitor Cable HDMI',
                'slug' => 'monitor-cable-hdmi',
                'description' => 'High-speed HDMI cable for 4K video and audio transmission.',
                'price' => 24.99,
                'sale_price' => null,
                'category_id' => $this->getCategoryId('electronics'),
                'images' => [
                    '/public/images/products/monitor-cable-hdmi-1.jpg',
                    '/public/images/products/monitor-cable-hdmi-2.jpg'
                ],
                'featured' => false,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 200,
                'sku' => 'MCH-006',
                'weight' => 0.1,
                'dimensions' => '2m length',
                'meta_title' => 'HDMI Cable - 4K High Speed',
                'meta_description' => 'High-speed HDMI cable supporting 4K video and audio transmission.',
                'meta_keywords' => 'hdmi, cable, 4k, video, audio',
            ],
            [
                'name' => 'External SSD 1TB',
                'slug' => 'external-ssd-1tb',
                'description' => 'Portable external SSD with USB-C connectivity and fast transfer speeds.',
                'price' => 149.99,
                'sale_price' => 129.99,
                'category_id' => $this->getCategoryId('electronics'),
                'images' => [
                    '/public/images/products/external-ssd-1tb-1.jpg',
                    '/public/images/products/external-ssd-1tb-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 40,
                'sku' => 'ESS-007',
                'weight' => 0.05,
                'dimensions' => '7x5x1 cm',
                'meta_title' => 'External SSD 1TB - Portable Storage',
                'meta_description' => 'Fast portable external SSD with USB-C connectivity for quick data transfer.',
                'meta_keywords' => 'ssd, external, storage, usb-c, portable',
            ],
            [
                'name' => 'Desk Lamp LED',
                'slug' => 'desk-lamp-led',
                'description' => 'Adjustable LED desk lamp with touch control and USB charging port.',
                'price' => 69.99,
                'sale_price' => 49.99,
                'category_id' => $this->getCategoryId('electronics'),
                'images' => [
                    '/public/images/products/desk-lamp-led-1.jpg',
                    '/public/images/products/desk-lamp-led-2.jpg'
                ],
                'featured' => false,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 80,
                'sku' => 'DLD-008',
                'weight' => 0.8,
                'dimensions' => '40x20x15 cm',
                'meta_title' => 'LED Desk Lamp - Touch Control',
                'meta_description' => 'Adjustable LED desk lamp with touch control and USB charging port.',
                'meta_keywords' => 'desk lamp, led, touch control, usb, adjustable',
            ],
            [
                'name' => 'Cable Management Kit',
                'slug' => 'cable-management-kit',
                'description' => 'Complete cable management solution with clips, ties, and organizers.',
                'price' => 39.99,
                'sale_price' => null,
                'category_id' => $this->getCategoryId('electronics'),
                'images' => [
                    '/public/images/products/cable-management-kit-1.jpg',
                    '/public/images/products/cable-management-kit-2.jpg'
                ],
                'featured' => false,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 90,
                'sku' => 'CMK-009',
                'weight' => 0.3,
                'dimensions' => '25x15x5 cm',
                'meta_title' => 'Cable Management Kit - Complete Solution',
                'meta_description' => 'Organize your cables with this complete cable management kit.',
                'meta_keywords' => 'cable management, organizer, clips, ties, desk',
            ],
            [
                'name' => 'Laptop Sleeve Neoprene',
                'slug' => 'laptop-sleeve-neoprene',
                'description' => 'Protective neoprene laptop sleeve with soft interior lining.',
                'price' => 34.99,
                'sale_price' => 24.99,
                'category_id' => $this->getCategoryId('electronics'),
                'images' => [
                    '/public/images/products/laptop-sleeve-neoprene-1.jpg',
                    '/public/images/products/laptop-sleeve-neoprene-2.jpg'
                ],
                'featured' => false,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 110,
                'sku' => 'LSN-010',
                'weight' => 0.2,
                'dimensions' => '35x25x2 cm',
                'meta_title' => 'Laptop Sleeve Neoprene - Protective Case',
                'meta_description' => 'Protect your laptop with this soft neoprene sleeve.',
                'meta_keywords' => 'laptop sleeve, neoprene, protective, case',
            ],
            [
                'name' => 'VR Headset Pro',
                'slug' => 'vr-headset-pro',
                'description' => 'High-resolution VR headset with motion tracking and hand controllers.',
                'price' => 599.99,
                'sale_price' => 499.99,
                'category_id' => $this->getCategoryId('electronics'),
                'images' => [
                    '/public/images/products/vr-headset-pro-1.jpg',
                    '/public/images/products/vr-headset-pro-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 25,
                'sku' => 'VHP-011',
                'weight' => 0.6,
                'dimensions' => '25x20x15 cm',
                'meta_title' => 'VR Headset Pro - High Resolution',
                'meta_description' => 'Immersive VR experience with high-resolution display and motion tracking.',
                'meta_keywords' => 'vr, headset, virtual reality, motion tracking',
            ],
            [
                'name' => 'Smart Home Hub',
                'slug' => 'smart-home-hub',
                'description' => 'Central smart home hub for controlling all your connected devices.',
                'price' => 199.99,
                'sale_price' => 149.99,
                'category_id' => $this->getCategoryId('electronics'),
                'images' => [
                    '/public/images/products/smart-home-hub-1.jpg',
                    '/public/images/products/smart-home-hub-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 35,
                'sku' => 'SHH-012',
                'weight' => 0.4,
                'dimensions' => '12x12x3 cm',
                'meta_title' => 'Smart Home Hub - Central Control',
                'meta_description' => 'Control all your smart home devices from one central hub.',
                'meta_keywords' => 'smart home, hub, iot, automation, control',
            ],
            // Audio & Video
            [
                'name' => 'E-Reader Pro',
                'slug' => 'e-reader-pro',
                'description' => 'High-resolution e-reader with built-in light and long battery life.',
                'price' => 199.99,
                'sale_price' => 149.99,
                'category_id' => $this->getCategoryId('audio-video'),
                'images' => [
                    '/public/images/products/e-reader-pro-1.jpg',
                    '/public/images/products/e-reader-pro-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 45,
                'sku' => 'ERP-013',
                'weight' => 0.2,
                'dimensions' => '15x10x1 cm',
                'meta_title' => 'E-Reader Pro - High Resolution Display',
                'meta_description' => 'Read comfortably with this high-resolution e-reader featuring built-in light.',
                'meta_keywords' => 'e-reader, ebook, reading, digital books',
            ],
            [
                'name' => 'Action Camera 4K',
                'slug' => 'action-camera-4k',
                'description' => 'Waterproof 4K action camera with image stabilization and WiFi.',
                'price' => 399.99,
                'sale_price' => 299.99,
                'category_id' => $this->getCategoryId('audio-video'),
                'images' => [
                    '/public/images/products/action-camera-4k-1.jpg',
                    '/public/images/products/action-camera-4k-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 30,
                'sku' => 'AC4K-014',
                'weight' => 0.1,
                'dimensions' => '6x4x3 cm',
                'meta_title' => 'Action Camera 4K - Waterproof',
                'meta_description' => 'Capture adventures with this waterproof 4K action camera.',
                'meta_keywords' => 'action camera, 4k, waterproof, sports, recording',
            ],
            [
                'name' => 'Smart Speaker Pro',
                'slug' => 'smart-speaker-pro',
                'description' => 'Premium smart speaker with voice assistant and superior sound quality.',
                'price' => 249.99,
                'sale_price' => 199.99,
                'category_id' => $this->getCategoryId('audio-video'),
                'images' => [
                    '/public/images/products/smart-speaker-pro-1.jpg',
                    '/public/images/products/smart-speaker-pro-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 55,
                'sku' => 'SSP-015',
                'weight' => 1.2,
                'dimensions' => '18x18x18 cm',
                'meta_title' => 'Smart Speaker Pro - Voice Assistant',
                'meta_description' => 'Premium smart speaker with voice assistant and superior audio quality.',
                'meta_keywords' => 'smart speaker, voice assistant, audio, premium',
            ],
            [
                'name' => 'Digital Camera Pro',
                'slug' => 'digital-camera-pro',
                'description' => 'Professional digital camera with 24MP sensor and 4K video recording.',
                'price' => 899.99,
                'sale_price' => 749.99,
                'category_id' => $this->getCategoryId('audio-video'),
                'images' => [
                    '/public/images/products/digital-camera-pro-1.jpg',
                    '/public/images/products/digital-camera-pro-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 20,
                'sku' => 'DCP-016',
                'weight' => 0.6,
                'dimensions' => '12x8x6 cm',
                'meta_title' => 'Digital Camera Pro - 24MP Sensor',
                'meta_description' => 'Professional digital camera with 24MP sensor and 4K video capabilities.',
                'meta_keywords' => 'digital camera, professional, 24mp, 4k video',
            ],
            [
                'name' => 'Wireless Mouse Pro',
                'slug' => 'wireless-mouse-pro',
                'description' => 'Ergonomic wireless mouse with precision tracking and long battery life.',
                'price' => 79.99,
                'sale_price' => 59.99,
                'category_id' => $this->getCategoryId('audio-video'),
                'images' => [
                    '/public/images/products/wireless-mouse-pro-1.jpg',
                    '/public/images/products/wireless-mouse-pro-2.jpg'
                ],
                'featured' => false,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 85,
                'sku' => 'WMP-017',
                'weight' => 0.1,
                'dimensions' => '12x6x4 cm',
                'meta_title' => 'Wireless Mouse Pro - Ergonomic Design',
                'meta_description' => 'Comfortable wireless mouse with precision tracking and ergonomic design.',
                'meta_keywords' => 'wireless mouse, ergonomic, precision, battery',
            ],
            [
                'name' => 'Mechanical Keyboard RGB',
                'slug' => 'mechanical-keyboard-rgb',
                'description' => 'RGB mechanical keyboard with customizable lighting and tactile switches.',
                'price' => 149.99,
                'sale_price' => 119.99,
                'category_id' => $this->getCategoryId('audio-video'),
                'images' => [
                    '/public/images/products/mechanical-keyboard-rgb-1.jpg',
                    '/public/images/products/mechanical-keyboard-rgb-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 65,
                'sku' => 'MKR-018',
                'weight' => 1.1,
                'dimensions' => '45x15x3 cm',
                'meta_title' => 'Mechanical Keyboard RGB - Customizable',
                'meta_description' => 'RGB mechanical keyboard with customizable lighting and tactile switches.',
                'meta_keywords' => 'mechanical keyboard, rgb, customizable, gaming',
            ],
            [
                'name' => 'Monitor Stand Adjustable',
                'slug' => 'monitor-stand-adjustable',
                'description' => 'Height-adjustable monitor stand with cable management and USB hub.',
                'price' => 129.99,
                'sale_price' => 99.99,
                'category_id' => $this->getCategoryId('audio-video'),
                'images' => [
                    '/public/images/products/monitor-stand-adjustable-1.jpg',
                    '/public/images/products/monitor-stand-adjustable-2.jpg'
                ],
                'featured' => false,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 40,
                'sku' => 'MSA-019',
                'weight' => 2.5,
                'dimensions' => '60x30x15 cm',
                'meta_title' => 'Monitor Stand Adjustable - Height Adjustable',
                'meta_description' => 'Ergonomic monitor stand with height adjustment and cable management.',
                'meta_keywords' => 'monitor stand, adjustable, ergonomic, cable management',
            ],
            [
                'name' => 'Webcam HD 1080p',
                'slug' => 'webcam-hd-1080p',
                'description' => 'HD webcam with 1080p recording, autofocus, and built-in microphone.',
                'price' => 89.99,
                'sale_price' => 69.99,
                'category_id' => $this->getCategoryId('audio-video'),
                'images' => [
                    '/public/images/products/webcam-hd-1080p-1.jpg',
                    '/public/images/products/webcam-hd-1080p-2.jpg'
                ],
                'featured' => false,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 70,
                'sku' => 'WH1080-020',
                'weight' => 0.2,
                'dimensions' => '10x5x3 cm',
                'meta_title' => 'Webcam HD 1080p - Autofocus',
                'meta_description' => 'HD webcam with 1080p recording, autofocus, and built-in microphone.',
                'meta_keywords' => 'webcam, hd, 1080p, autofocus, microphone',
            ],
            [
                'name' => 'Laptop Cooling Pad',
                'slug' => 'laptop-cooling-pad',
                'description' => 'USB-powered laptop cooling pad with adjustable fan speeds.',
                'price' => 49.99,
                'sale_price' => 34.99,
                'category_id' => $this->getCategoryId('audio-video'),
                'images' => [
                    '/public/images/products/laptop-cooling-pad-1.jpg',
                    '/public/images/products/laptop-cooling-pad-2.jpg'
                ],
                'featured' => false,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 95,
                'sku' => 'LCP-021',
                'weight' => 0.8,
                'dimensions' => '35x25x3 cm',
                'meta_title' => 'Laptop Cooling Pad - USB Powered',
                'meta_description' => 'Keep your laptop cool with this USB-powered cooling pad.',
                'meta_keywords' => 'laptop cooling, cooling pad, usb, fan',
            ],
            [
                'name' => 'Gaming Headset Pro',
                'slug' => 'gaming-headset-pro',
                'description' => 'Professional gaming headset with 7.1 surround sound and noise cancellation.',
                'price' => 199.99,
                'sale_price' => 149.99,
                'category_id' => $this->getCategoryId('audio-video'),
                'images' => [
                    '/public/images/products/gaming-headset-rgb-1.jpg',
                    '/public/images/products/gaming-headset-rgb-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 35,
                'sku' => 'GHP-022',
                'weight' => 0.4,
                'dimensions' => '25x20x10 cm',
                'meta_title' => 'Gaming Headset Pro - 7.1 Surround',
                'meta_description' => 'Professional gaming headset with 7.1 surround sound and noise cancellation.',
                'meta_keywords' => 'gaming headset, surround sound, noise cancellation, gaming',
            ],
            [
                'name' => 'Studio Microphone USB',
                'slug' => 'studio-microphone-usb',
                'description' => 'Professional USB studio microphone with cardioid pickup pattern.',
                'price' => 159.99,
                'sale_price' => 129.99,
                'category_id' => $this->getCategoryId('audio-video'),
                'images' => [
                    '/public/images/products/studio-monitor-headphones-1.jpg',
                    '/public/images/products/studio-monitor-headphones-2.jpg'
                ],
                'featured' => false,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 25,
                'sku' => 'SMU-023',
                'weight' => 0.6,
                'dimensions' => '20x8x8 cm',
                'meta_title' => 'Studio Microphone USB - Professional',
                'meta_description' => 'Professional USB studio microphone with cardioid pickup pattern.',
                'meta_keywords' => 'studio microphone, usb, professional, recording',
            ],
            [
                'name' => 'Audio Interface Pro',
                'slug' => 'audio-interface-pro',
                'description' => 'Professional audio interface with multiple inputs and outputs.',
                'price' => 299.99,
                'sale_price' => 249.99,
                'category_id' => $this->getCategoryId('audio-video'),
                'images' => [
                    '/public/images/products/high-end-audiophile-headphones-1.jpg',
                    '/public/images/products/high-end-audiophile-headphones-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 15,
                'sku' => 'AIP-024',
                'weight' => 1.2,
                'dimensions' => '25x15x5 cm',
                'meta_title' => 'Audio Interface Pro - Multiple I/O',
                'meta_description' => 'Professional audio interface with multiple inputs and outputs for recording.',
                'meta_keywords' => 'audio interface, professional, recording, multiple inputs',
            ],
            // Gaming
            [
                'name' => 'Gaming Mouse RGB',
                'slug' => 'gaming-mouse-rgb',
                'description' => 'High-precision gaming mouse with RGB lighting and programmable buttons.',
                'price' => 89.99,
                'sale_price' => 69.99,
                'category_id' => $this->getCategoryId('gaming'),
                'images' => [
                    '/public/images/products/gaming-mouse-1.jpg',
                    '/public/images/products/gaming-mouse-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 60,
                'sku' => 'GMR-025',
                'weight' => 0.12,
                'dimensions' => '12x6x4 cm',
                'meta_title' => 'Gaming Mouse RGB - High Precision',
                'meta_description' => 'High-precision gaming mouse with RGB lighting and programmable buttons.',
                'meta_keywords' => 'gaming mouse, rgb, precision, programmable',
            ],
            [
                'name' => 'Gaming Keyboard Mechanical',
                'slug' => 'gaming-keyboard-mechanical',
                'description' => 'Mechanical gaming keyboard with Cherry MX switches and RGB backlighting.',
                'price' => 179.99,
                'sale_price' => 149.99,
                'category_id' => $this->getCategoryId('gaming'),
                'images' => [
                    '/public/images/products/gaming-mechanical-keyboard-1.jpg',
                    '/public/images/products/gaming-mechanical-keyboard-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 45,
                'sku' => 'GKM-026',
                'weight' => 1.2,
                'length' => 45.0,
                'width' => 15.0,
                'height' => 3.0,
                'meta_title' => 'Gaming Keyboard Mechanical - Cherry MX',
                'meta_description' => 'Mechanical gaming keyboard with Cherry MX switches and RGB backlighting.',
                'meta_keywords' => 'gaming keyboard, mechanical, cherry mx, rgb',
            ],
            [
                'name' => 'Gaming Chair Pro',
                'slug' => 'gaming-chair-pro',
                'description' => 'Ergonomic gaming chair with lumbar support and adjustable armrests.',
                'price' => 399.99,
                'sale_price' => 299.99,
                'category_id' => $this->getCategoryId('gaming'),
                'images' => [
                    '/public/images/products/gaming-console-pro-1.jpg',
                    '/public/images/products/gaming-console-pro-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 25,
                'sku' => 'GCP-027',
                'weight' => 25.0,
                'dimensions' => '70x70x120 cm',
                'meta_title' => 'Gaming Chair Pro - Ergonomic',
                'meta_description' => 'Ergonomic gaming chair with lumbar support and adjustable features.',
                'meta_keywords' => 'gaming chair, ergonomic, lumbar support, adjustable',
            ],
            [
                'name' => 'Gaming Monitor 144Hz',
                'slug' => 'gaming-monitor-144hz',
                'description' => '27-inch gaming monitor with 144Hz refresh rate and 1ms response time.',
                'price' => 349.99,
                'sale_price' => 279.99,
                'category_id' => $this->getCategoryId('gaming'),
                'images' => [
                    '/public/images/products/smart-tv-55-inch-1.jpg',
                    '/public/images/products/smart-tv-55-inch-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 30,
                'sku' => 'GM144-028',
                'weight' => 6.5,
                'dimensions' => '62x37x5 cm',
                'meta_title' => 'Gaming Monitor 144Hz - 1ms Response',
                'meta_description' => 'High-performance gaming monitor with 144Hz refresh rate and 1ms response time.',
                'meta_keywords' => 'gaming monitor, 144hz, 1ms, high refresh rate',
            ],
            [
                'name' => 'Gaming Desk Mat',
                'slug' => 'gaming-desk-mat',
                'description' => 'Large gaming desk mat with RGB lighting and mouse pad surface.',
                'price' => 79.99,
                'sale_price' => 59.99,
                'category_id' => $this->getCategoryId('gaming'),
                'images' => [
                    '/public/images/products/monitor-stand-adjustable-1.jpg',
                    '/public/images/products/monitor-stand-adjustable-2.jpg'
                ],
                'featured' => false,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 80,
                'sku' => 'GDM-029',
                'weight' => 0.8,
                'dimensions' => '90x40x0.5 cm',
                'meta_title' => 'Gaming Desk Mat - RGB Lighting',
                'meta_description' => 'Large gaming desk mat with RGB lighting and premium mouse pad surface.',
                'meta_keywords' => 'gaming desk mat, rgb, mouse pad, large',
            ],
            [
                'name' => 'Gaming Controller Pro',
                'slug' => 'gaming-controller-pro',
                'description' => 'Wireless gaming controller with customizable buttons and RGB lighting.',
                'price' => 129.99,
                'sale_price' => 99.99,
                'category_id' => $this->getCategoryId('gaming'),
                'images' => [
                    '/public/images/products/gaming-console-pro-1.jpg',
                    '/public/images/products/gaming-console-pro-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 50,
                'sku' => 'GCP-030',
                'weight' => 0.25,
                'dimensions' => '15x10x6 cm',
                'meta_title' => 'Gaming Controller Pro - Wireless',
                'meta_description' => 'Wireless gaming controller with customizable buttons and RGB lighting.',
                'meta_keywords' => 'gaming controller, wireless, customizable, rgb',
            ],
            [
                'name' => 'Gaming Mousepad XXL',
                'slug' => 'gaming-mousepad-xxl',
                'description' => 'Extra large gaming mousepad with stitched edges and non-slip base.',
                'price' => 39.99,
                'sale_price' => 29.99,
                'category_id' => $this->getCategoryId('gaming'),
                'images' => [
                    '/public/images/products/monitor-stand-adjustable-1.jpg',
                    '/public/images/products/monitor-stand-adjustable-2.jpg'
                ],
                'featured' => false,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 100,
                'sku' => 'GMXXL-031',
                'weight' => 0.3,
                'dimensions' => '80x30x0.3 cm',
                'meta_title' => 'Gaming Mousepad XXL - Stitched Edges',
                'meta_description' => 'Extra large gaming mousepad with stitched edges and non-slip base.',
                'meta_keywords' => 'gaming mousepad, xxl, stitched edges, non-slip',
            ],
            [
                'name' => 'Gaming Headset Wireless',
                'slug' => 'gaming-headset-wireless',
                'description' => 'Wireless gaming headset with 7.1 surround sound and noise cancellation.',
                'price' => 199.99,
                'sale_price' => 159.99,
                'category_id' => $this->getCategoryId('gaming'),
                'images' => [
                    '/public/images/products/gaming-headset-rgb-1.jpg',
                    '/public/images/products/gaming-headset-rgb-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 40,
                'sku' => 'GHW-032',
                'weight' => 0.35,
                'dimensions' => '25x20x10 cm',
                'meta_title' => 'Gaming Headset Wireless - 7.1 Surround',
                'meta_description' => 'Wireless gaming headset with 7.1 surround sound and noise cancellation.',
                'meta_keywords' => 'gaming headset, wireless, surround sound, noise cancellation',
            ],
            [
                'name' => 'Gaming Laptop Stand',
                'slug' => 'gaming-laptop-stand',
                'description' => 'Adjustable laptop stand with cooling fans and RGB lighting.',
                'price' => 89.99,
                'sale_price' => 69.99,
                'category_id' => $this->getCategoryId('gaming'),
                'images' => [
                    '/public/images/products/laptop-cooling-pad-1.jpg',
                    '/public/images/products/laptop-cooling-pad-2.jpg'
                ],
                'featured' => false,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 35,
                'sku' => 'GLS-033',
                'weight' => 1.5,
                'dimensions' => '40x30x8 cm',
                'meta_title' => 'Gaming Laptop Stand - Cooling Fans',
                'meta_description' => 'Adjustable laptop stand with cooling fans and RGB lighting.',
                'meta_keywords' => 'gaming laptop stand, cooling fans, rgb, adjustable',
            ],
            [
                'name' => 'Gaming Webcam 4K',
                'slug' => 'gaming-webcam-4k',
                'description' => '4K gaming webcam with HDR and built-in ring light.',
                'price' => 199.99,
                'sale_price' => 149.99,
                'category_id' => $this->getCategoryId('gaming'),
                'images' => [
                    '/public/images/products/webcam-hd-1080p-1.jpg',
                    '/public/images/products/webcam-hd-1080p-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 25,
                'sku' => 'GW4K-034',
                'weight' => 0.3,
                'dimensions' => '12x6x4 cm',
                'meta_title' => 'Gaming Webcam 4K - HDR',
                'meta_description' => '4K gaming webcam with HDR and built-in ring light.',
                'meta_keywords' => 'gaming webcam, 4k, hdr, ring light',
            ],
            [
                'name' => 'Gaming Microphone USB',
                'slug' => 'gaming-microphone-usb',
                'description' => 'Professional USB gaming microphone with noise suppression.',
                'price' => 129.99,
                'sale_price' => 99.99,
                'category_id' => $this->getCategoryId('gaming'),
                'images' => [
                    '/public/images/products/studio-monitor-headphones-1.jpg',
                    '/public/images/products/studio-monitor-headphones-2.jpg'
                ],
                'featured' => false,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 45,
                'sku' => 'GMU-035',
                'weight' => 0.4,
                'dimensions' => '18x8x8 cm',
                'meta_title' => 'Gaming Microphone USB - Noise Suppression',
                'meta_description' => 'Professional USB gaming microphone with noise suppression.',
                'meta_keywords' => 'gaming microphone, usb, noise suppression, professional',
            ],
            [
                'name' => 'Gaming Router WiFi 6',
                'slug' => 'gaming-router-wifi-6',
                'description' => 'High-performance WiFi 6 gaming router with QoS optimization.',
                'price' => 299.99,
                'sale_price' => 249.99,
                'category_id' => $this->getCategoryId('gaming'),
                'images' => [
                    '/public/images/products/smart-home-hub-1.jpg',
                    '/public/images/products/smart-home-hub-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 20,
                'sku' => 'GRW6-036',
                'weight' => 1.2,
                'dimensions' => '25x20x5 cm',
                'meta_title' => 'Gaming Router WiFi 6 - QoS Optimization',
                'meta_description' => 'High-performance WiFi 6 gaming router with QoS optimization.',
                'meta_keywords' => 'gaming router, wifi 6, qos, high performance',
            ],
            // Computer Accessories
            [
                'name' => 'USB Hub 4-Port',
                'slug' => 'usb-hub-4-port',
                'description' => 'Compact USB hub with 4 ports and LED indicators.',
                'price' => 24.99,
                'sale_price' => 19.99,
                'category_id' => $this->getCategoryId('computer-accessories'),
                'images' => [
                    '/public/images/products/usb-hub-1.jpg',
                    '/public/images/products/usb-hub-1.jpg'
                ],
                'featured' => false,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 120,
                'sku' => 'UH4P-037',
                'weight' => 0.1,
                'dimensions' => '8x3x1 cm',
                'meta_title' => 'USB Hub 4-Port - Compact',
                'meta_description' => 'Compact USB hub with 4 ports and LED indicators.',
                'meta_keywords' => 'usb hub, 4 port, compact, led indicators',
            ],
            [
                'name' => 'Laptop Stand Aluminum',
                'slug' => 'laptop-stand-aluminum',
                'description' => 'Adjustable aluminum laptop stand with ventilation slots.',
                'price' => 59.99,
                'sale_price' => 44.99,
                'category_id' => $this->getCategoryId('computer-accessories'),
                'images' => [
                    '/public/images/products/laptop-cooling-pad-1.jpg',
                    '/public/images/products/laptop-cooling-pad-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 75,
                'sku' => 'LSA-038',
                'weight' => 0.8,
                'dimensions' => '35x25x3 cm',
                'meta_title' => 'Laptop Stand Aluminum - Adjustable',
                'meta_description' => 'Adjustable aluminum laptop stand with ventilation slots.',
                'meta_keywords' => 'laptop stand, aluminum, adjustable, ventilation',
            ],
            [
                'name' => 'Wireless Charger Stand',
                'slug' => 'wireless-charger-stand',
                'description' => 'Adjustable wireless charging stand for smartphones and smartwatches.',
                'price' => 49.99,
                'sale_price' => 34.99,
                'category_id' => $this->getCategoryId('computer-accessories'),
                'images' => [
                    '/public/images/products/wireless-charger-pad-1.jpg',
                    '/public/images/products/wireless-charger-pad-2.jpg'
                ],
                'featured' => false,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 90,
                'sku' => 'WCS-039',
                'weight' => 0.3,
                'dimensions' => '12x8x15 cm',
                'meta_title' => 'Wireless Charger Stand - Adjustable',
                'meta_description' => 'Adjustable wireless charging stand for smartphones and smartwatches.',
                'meta_keywords' => 'wireless charger, stand, adjustable, smartphone, smartwatch',
            ],
            [
                'name' => 'Monitor Arm Dual',
                'slug' => 'monitor-arm-dual',
                'description' => 'Dual monitor arm with gas spring and cable management.',
                'price' => 199.99,
                'sale_price' => 149.99,
                'category_id' => $this->getCategoryId('computer-accessories'),
                'images' => [
                    '/public/images/products/monitor-stand-adjustable-1.jpg',
                    '/public/images/products/monitor-stand-adjustable-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 30,
                'sku' => 'MAD-040',
                'weight' => 8.5,
                'dimensions' => '120x40x10 cm',
                'meta_title' => 'Monitor Arm Dual - Gas Spring',
                'meta_description' => 'Dual monitor arm with gas spring and cable management.',
                'meta_keywords' => 'monitor arm, dual, gas spring, cable management',
            ],
            [
                'name' => 'Keyboard Wrist Rest',
                'slug' => 'keyboard-wrist-rest',
                'description' => 'Ergonomic wrist rest with memory foam and gel padding.',
                'price' => 29.99,
                'sale_price' => 19.99,
                'category_id' => $this->getCategoryId('computer-accessories'),
                'images' => [
                    '/public/images/products/mechanical-keyboard-rgb-1.jpg',
                    '/public/images/products/mechanical-keyboard-rgb-2.jpg'
                ],
                'featured' => false,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 150,
                'sku' => 'KWR-041',
                'weight' => 0.2,
                'dimensions' => '45x8x2 cm',
                'meta_title' => 'Keyboard Wrist Rest - Memory Foam',
                'meta_description' => 'Ergonomic wrist rest with memory foam and gel padding.',
                'meta_keywords' => 'keyboard wrist rest, ergonomic, memory foam, gel',
            ],
            [
                'name' => 'Mouse Pad Gaming',
                'slug' => 'mouse-pad-gaming',
                'description' => 'Large gaming mouse pad with stitched edges and non-slip base.',
                'price' => 19.99,
                'sale_price' => 14.99,
                'category_id' => $this->getCategoryId('computer-accessories'),
                'images' => [
                    '/public/images/products/monitor-stand-adjustable-1.jpg',
                    '/public/images/products/monitor-stand-adjustable-2.jpg'
                ],
                'featured' => false,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 200,
                'sku' => 'MPG-042',
                'weight' => 0.2,
                'dimensions' => '80x30x0.3 cm',
                'meta_title' => 'Mouse Pad Gaming - Large',
                'meta_description' => 'Large gaming mouse pad with stitched edges and non-slip base.',
                'meta_keywords' => 'mouse pad, gaming, large, stitched edges',
            ],
            [
                'name' => 'Desk Organizer Bamboo',
                'slug' => 'desk-organizer-bamboo',
                'description' => 'Bamboo desk organizer with multiple compartments and drawers.',
                'price' => 79.99,
                'sale_price' => 59.99,
                'category_id' => $this->getCategoryId('computer-accessories'),
                'images' => [
                    '/public/images/products/cable-management-kit-1.jpg',
                    '/public/images/products/cable-management-kit-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 50,
                'sku' => 'DOB-043',
                'weight' => 1.5,
                'dimensions' => '30x20x15 cm',
                'meta_title' => 'Desk Organizer Bamboo - Multiple Compartments',
                'meta_description' => 'Bamboo desk organizer with multiple compartments and drawers.',
                'meta_keywords' => 'desk organizer, bamboo, compartments, drawers',
            ],
            [
                'name' => 'Cable Tray Under Desk',
                'slug' => 'cable-tray-under-desk',
                'description' => 'Under-desk cable tray with mounting hardware and cable clips.',
                'price' => 39.99,
                'sale_price' => 29.99,
                'category_id' => $this->getCategoryId('computer-accessories'),
                'images' => [
                    '/public/images/products/cable-management-kit-1.jpg',
                    '/public/images/products/cable-management-kit-2.jpg'
                ],
                'featured' => false,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 80,
                'sku' => 'CTUD-044',
                'weight' => 0.8,
                'dimensions' => '60x10x5 cm',
                'meta_title' => 'Cable Tray Under Desk - Mounting Hardware',
                'meta_description' => 'Under-desk cable tray with mounting hardware and cable clips.',
                'meta_keywords' => 'cable tray, under desk, mounting, cable clips',
            ],
            [
                'name' => 'Monitor Light Bar',
                'slug' => 'monitor-light-bar',
                'description' => 'LED monitor light bar with touch control and USB power.',
                'price' => 89.99,
                'sale_price' => 69.99,
                'category_id' => $this->getCategoryId('computer-accessories'),
                'images' => [
                    '/public/images/products/desk-lamp-led-1.jpg',
                    '/public/images/products/desk-lamp-led-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 40,
                'sku' => 'MLB-045',
                'weight' => 0.4,
                'dimensions' => '50x3x2 cm',
                'meta_title' => 'Monitor Light Bar - LED Touch Control',
                'meta_description' => 'LED monitor light bar with touch control and USB power.',
                'meta_keywords' => 'monitor light bar, led, touch control, usb',
            ],
            [
                'name' => 'Laptop Sleeve 15-inch',
                'slug' => 'laptop-sleeve-15-inch',
                'description' => 'Protective laptop sleeve for 15-inch laptops with soft interior.',
                'price' => 34.99,
                'sale_price' => 24.99,
                'category_id' => $this->getCategoryId('computer-accessories'),
                'images' => [
                    '/public/images/products/laptop-sleeve-neoprene-1.jpg',
                    '/public/images/products/laptop-sleeve-neoprene-2.jpg'
                ],
                'featured' => false,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 100,
                'sku' => 'LS15-046',
                'weight' => 0.3,
                'dimensions' => '40x30x2 cm',
                'meta_title' => 'Laptop Sleeve 15-inch - Protective',
                'meta_description' => 'Protective laptop sleeve for 15-inch laptops with soft interior.',
                'meta_keywords' => 'laptop sleeve, 15 inch, protective, soft interior',
            ],
            [
                'name' => 'USB-C Cable 2m',
                'slug' => 'usb-c-cable-2m',
                'description' => 'High-speed USB-C cable with 2-meter length and braided design.',
                'price' => 19.99,
                'sale_price' => 14.99,
                'category_id' => $this->getCategoryId('computer-accessories'),
                'images' => [
                    '/public/images/products/monitor-cable-hdmi-1.jpg',
                    '/public/images/products/monitor-cable-hdmi-2.jpg'
                ],
                'featured' => false,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 180,
                'sku' => 'UCC2M-047',
                'weight' => 0.1,
                'dimensions' => '2m length',
                'meta_title' => 'USB-C Cable 2m - High Speed',
                'meta_description' => 'High-speed USB-C cable with 2-meter length and braided design.',
                'meta_keywords' => 'usb-c cable, 2m, high speed, braided',
            ],
            [
                'name' => 'Desk Mat Leather',
                'slug' => 'desk-mat-leather',
                'description' => 'Premium leather desk mat with stitched edges and non-slip base.',
                'price' => 99.99,
                'sale_price' => 79.99,
                'category_id' => $this->getCategoryId('computer-accessories'),
                'images' => [
                    '/public/images/products/monitor-stand-adjustable-1.jpg',
                    '/public/images/products/monitor-stand-adjustable-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 35,
                'sku' => 'DML-048',
                'weight' => 1.2,
                'dimensions' => '90x40x0.5 cm',
                'meta_title' => 'Desk Mat Leather - Premium',
                'meta_description' => 'Premium leather desk mat with stitched edges and non-slip base.',
                'meta_keywords' => 'desk mat, leather, premium, stitched edges',
            ],
            // Wearables
            [
                'name' => 'Smartwatch Pro',
                'slug' => 'smartwatch-pro',
                'description' => 'Advanced smartwatch with health monitoring and GPS tracking.',
                'price' => 399.99,
                'sale_price' => 299.99,
                'category_id' => $this->getCategoryId('wearables'),
                'images' => [
                    '/public/images/products/premium-smart-watch-pro-1.jpg',
                    '/public/images/products/premium-smart-watch-pro-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 40,
                'sku' => 'SWP-049',
                'weight' => 0.05,
                'dimensions' => '4x4x1 cm',
                'meta_title' => 'Smartwatch Pro - Health Monitoring',
                'meta_description' => 'Advanced smartwatch with health monitoring and GPS tracking.',
                'meta_keywords' => 'smartwatch, health monitoring, gps, fitness',
            ],
            [
                'name' => 'Fitness Tracker Band',
                'slug' => 'fitness-tracker-band',
                'description' => 'Waterproof fitness tracker with heart rate monitoring and sleep tracking.',
                'price' => 149.99,
                'sale_price' => 119.99,
                'category_id' => $this->getCategoryId('wearables'),
                'images' => [
                    '/public/images/products/fitness-tracker-band-1.jpg',
                    '/public/images/products/fitness-tracker-band-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 80,
                'sku' => 'FTB-050',
                'weight' => 0.02,
                'dimensions' => '20x2x1 cm',
                'meta_title' => 'Fitness Tracker Band - Heart Rate',
                'meta_description' => 'Waterproof fitness tracker with heart rate monitoring and sleep tracking.',
                'meta_keywords' => 'fitness tracker, heart rate, sleep tracking, waterproof',
            ],
            [
                'name' => 'Wireless Earbuds Pro',
                'slug' => 'wireless-earbuds-pro',
                'description' => 'Premium wireless earbuds with active noise cancellation and wireless charging.',
                'price' => 249.99,
                'sale_price' => 199.99,
                'category_id' => $this->getCategoryId('wearables'),
                'images' => [
                    '/public/images/products/wireless-earbuds-pro-1.jpg',
                    '/public/images/products/wireless-earbuds-pro-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 60,
                'sku' => 'WEP-051',
                'weight' => 0.05,
                'dimensions' => '6x4x2 cm',
                'meta_title' => 'Wireless Earbuds Pro - Noise Cancellation',
                'meta_description' => 'Premium wireless earbuds with active noise cancellation and wireless charging.',
                'meta_keywords' => 'wireless earbuds, noise cancellation, wireless charging, premium',
            ],
            [
                'name' => 'VR Headset Standalone',
                'slug' => 'vr-headset-standalone',
                'description' => 'Standalone VR headset with built-in processing and 6DOF tracking.',
                'price' => 599.99,
                'sale_price' => 499.99,
                'category_id' => $this->getCategoryId('wearables'),
                'images' => [
                    '/public/images/products/vr-headset-pro-1.jpg',
                    '/public/images/products/vr-headset-pro-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 20,
                'sku' => 'VRHS-052',
                'weight' => 0.6,
                'dimensions' => '25x20x15 cm',
                'meta_title' => 'VR Headset Standalone - 6DOF Tracking',
                'meta_description' => 'Standalone VR headset with built-in processing and 6DOF tracking.',
                'meta_keywords' => 'vr headset, standalone, 6dof, virtual reality',
            ],
            [
                'name' => 'Smart Ring Health',
                'slug' => 'smart-ring-health',
                'description' => 'Sleek smart ring with health monitoring and NFC payment capabilities.',
                'price' => 299.99,
                'sale_price' => 249.99,
                'category_id' => $this->getCategoryId('wearables'),
                'images' => [
                    '/public/images/products/smart-ring-health-monitor-1.jpg',
                    '/public/images/products/smart-ring-health-monitor-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 35,
                'sku' => 'SRH-053',
                'weight' => 0.01,
                'dimensions' => '2x2x0.5 cm',
                'meta_title' => 'Smart Ring Health - NFC Payment',
                'meta_description' => 'Sleek smart ring with health monitoring and NFC payment capabilities.',
                'meta_keywords' => 'smart ring, health monitoring, nfc payment, sleek',
            ],
            [
                'name' => 'Bluetooth Headphones Sport',
                'slug' => 'bluetooth-headphones-sport',
                'description' => 'Sports Bluetooth headphones with sweat resistance and secure fit.',
                'price' => 129.99,
                'sale_price' => 99.99,
                'category_id' => $this->getCategoryId('wearables'),
                'images' => [
                    '/public/images/products/wireless-earbuds-sport-1.jpg',
                    '/public/images/products/wireless-earbuds-sport-2.jpg'
                ],
                'featured' => false,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 70,
                'sku' => 'BHS-054',
                'weight' => 0.15,
                'dimensions' => '20x15x8 cm',
                'meta_title' => 'Bluetooth Headphones Sport - Sweat Resistant',
                'meta_description' => 'Sports Bluetooth headphones with sweat resistance and secure fit.',
                'meta_keywords' => 'bluetooth headphones, sport, sweat resistant, secure fit',
            ],
            [
                'name' => 'Smart Glasses AR',
                'slug' => 'smart-glasses-ar',
                'description' => 'Augmented reality smart glasses with display overlay and voice control.',
                'price' => 899.99,
                'sale_price' => 749.99,
                'category_id' => $this->getCategoryId('wearables'),
                'images' => [
                    '/public/images/products/smart-glasses-ar-1.jpg',
                    '/public/images/products/smart-glasses-ar-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 15,
                'sku' => 'SGAR-055',
                'weight' => 0.08,
                'dimensions' => '15x5x3 cm',
                'meta_title' => 'Smart Glasses AR - Display Overlay',
                'meta_description' => 'Augmented reality smart glasses with display overlay and voice control.',
                'meta_keywords' => 'smart glasses, ar, augmented reality, voice control',
            ],
            [
                'name' => 'Fitness Watch GPS',
                'slug' => 'fitness-watch-gps',
                'description' => 'GPS fitness watch with multi-sport tracking and long battery life.',
                'price' => 199.99,
                'sale_price' => 159.99,
                'category_id' => $this->getCategoryId('wearables'),
                'images' => [
                    '/public/images/products/gps-sports-watch-1.jpg',
                    '/public/images/products/gps-sports-watch-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 55,
                'sku' => 'FWGPS-056',
                'weight' => 0.06,
                'dimensions' => '4x4x1 cm',
                'meta_title' => 'Fitness Watch GPS - Multi-Sport',
                'meta_description' => 'GPS fitness watch with multi-sport tracking and long battery life.',
                'meta_keywords' => 'fitness watch, gps, multi-sport, battery life',
            ],
            [
                'name' => 'Wireless Charging Pad',
                'slug' => 'wireless-charging-pad-wearables',
                'description' => 'Fast wireless charging pad for smartwatches and earbuds.',
                'price' => 59.99,
                'sale_price' => 44.99,
                'category_id' => $this->getCategoryId('wearables'),
                'images' => [
                    '/public/images/products/wireless-charger-pad-1.jpg',
                    '/public/images/products/wireless-charger-pad-2.jpg'
                ],
                'featured' => false,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 90,
                'sku' => 'WCPW-057',
                'weight' => 0.2,
                'dimensions' => '10x10x1 cm',
                'meta_title' => 'Wireless Charging Pad - Fast Charge',
                'meta_description' => 'Fast wireless charging pad for smartwatches and earbuds.',
                'meta_keywords' => 'wireless charging, fast charge, smartwatch, earbuds',
            ],
            [
                'name' => 'Smart Band Sleep',
                'slug' => 'smart-band-sleep',
                'description' => 'Sleep tracking smart band with advanced sleep analysis and insights.',
                'price' => 179.99,
                'sale_price' => 139.99,
                'category_id' => $this->getCategoryId('wearables'),
                'images' => [
                    '/public/images/products/sleep-tracking-headband-1.jpg',
                    '/public/images/products/sleep-tracking-headband-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 45,
                'sku' => 'SBS-058',
                'weight' => 0.03,
                'dimensions' => '18x2x1 cm',
                'meta_title' => 'Smart Band Sleep - Sleep Analysis',
                'meta_description' => 'Sleep tracking smart band with advanced sleep analysis and insights.',
                'meta_keywords' => 'smart band, sleep tracking, sleep analysis, insights',
            ],
            [
                'name' => 'Bluetooth Neckband',
                'slug' => 'bluetooth-neckband',
                'description' => 'Comfortable Bluetooth neckband with magnetic earbuds and long battery.',
                'price' => 79.99,
                'sale_price' => 59.99,
                'category_id' => $this->getCategoryId('wearables'),
                'images' => [
                    '/public/images/products/wireless-earbuds-pro-1.jpg',
                    '/public/images/products/wireless-earbuds-pro-2.jpg'
                ],
                'featured' => false,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 85,
                'sku' => 'BN-059',
                'weight' => 0.08,
                'dimensions' => '30x8x2 cm',
                'meta_title' => 'Bluetooth Neckband - Magnetic Earbuds',
                'meta_description' => 'Comfortable Bluetooth neckband with magnetic earbuds and long battery.',
                'meta_keywords' => 'bluetooth neckband, magnetic earbuds, long battery, comfortable',
            ],
            [
                'name' => 'Smart Scale Body',
                'slug' => 'smart-scale-body',
                'description' => 'Smart body scale with body composition analysis and app sync.',
                'price' => 149.99,
                'sale_price' => 119.99,
                'category_id' => $this->getCategoryId('wearables'),
                'images' => [
                    '/public/images/products/smart-scale-body-analyzer-1.jpg',
                    '/public/images/products/smart-scale-body-analyzer-2.jpg'
                ],
                'featured' => true,
                'status' => 'active',
                'in_stock' => true,
                'stock_quantity' => 30,
                'sku' => 'SSB-060',
                'weight' => 2.5,
                'dimensions' => '30x30x3 cm',
                'meta_title' => 'Smart Scale Body - Composition Analysis',
                'meta_description' => 'Smart body scale with body composition analysis and app sync.',
                'meta_keywords' => 'smart scale, body composition, analysis, app sync',
            ],
        ];

        foreach ($products as $productData) {
            Product::create($productData);
        }
    }

    private function getCategoryId(string $slug): int
    {
        $category = Category::where('slug', $slug)->first();
        if (!$category) {
            throw new \Exception("Category with slug '{$slug}' not found");
        }
        return $category->id;
    }
}
